### ISSUE TITLE
Enhancement: Environment Variables

### ISSUE THREAD

**Issue by jpotts18** [nficano/python-lambda#26]
What do you think about adding an .env file into every lambda folder? Sending environment variables can be accomplished after uploading the zip file. 

```
# http://docs.aws.amazon.com/lambda/latest/dg/env_variables.html
aws lambda create-function \
    --region us-east-1
    --function-name myTestFunction
    --zip-file fileb://path/package.zip
    --role role-arn
    --environment Variables={LD_LIBRARY_PATH=/usr/bin/test/lib64}
    --handler index.handler
    --runtime nodejs4.3
    --profile default
```

**Comment by jmeekhof** [comment]
This would be a great feature to add. Definitely on the roadmap.

**Comment by jmeekhof** [comment]
Taking a peak through the code, I think we the support is there to translate _some_ local env variables to the lambda instance.

Take a look at this code:
https://github.com/nficano/python-lambda/blob/master/aws_lambda/aws_lambda.py#L364-L370

If you name a local variable `LAMBDA_foo`, it should translate to `foo` in the lambda instance.

That being said, I like the idea of a singular file that handles the variables instead of this method.

Also, I'm unsure of what how these variables are handled upon updates to a function (opposed to the creation of a new function).

**Comment by jmeekhof** [comment]
See issue #11

**Comment by jmeekhof** [comment]
This feature has been added and merged to master. It'll be generally available next release. Meanwhile, you can grab it off the master branch.
